on: [push, workflow_dispatch]
name: Build
jobs:
  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            submodules: true
      - name: Install Dependencies
        run: sudo apt-get install -y mtools
      - name: Build
        run: make ARCH=aarch64
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kuroko.efi
          path: |
            kuroko.efi
            cdimage.iso
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            submodules: true
      - name: Install Dependencies
        run: sudo apt-get install -y mtools
      - name: Build
        run: make ARCH=x86_64
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kuroko.efi
          path: |
            kuroko.efi
            cdimage.iso

